<script setup lang="ts">
import { ref } from 'vue'
import { ChatDotRound, Document, UploadFilled } from '@element-plus/icons-vue'
import { sendCustomerMessage } from '@/apis/customerService'

const question = ref('')
const answer = ref('')
const asking = ref(false)
const files = ref([{ name: '易going客服知识库.md', size: '1.2 KB', status: '已向量化', chunks: 4 }])
const ask = async () => { if (!question.value.trim()) return; asking.value = true; try { answer.value = (await sendCustomerMessage(question.value)).data.answer } catch { answer.value = '模型尚未配置。请在服务器环境变量中填写 EASYGOING_AI_BASE_URL、EASYGOING_AI_API_KEY，并将 EASYGOING_AI_ENABLED 设为 true。' } finally { asking.value = false } }
const beforeUpload = (file: File) => { files.value.push({ name: file.name, size: `${Math.ceil(file.size / 1024)} KB`, status: '等待模型配置', chunks: 0 }); return false }
</script>
<template><div class="ai-page"><section class="hero"><div><span>AI CUSTOMER SERVICE</span><h1>智能客服中心</h1><p>管理员维护知识，消费者获得一致、可追溯的回答。</p></div><el-tag type="warning">模型待配置</el-tag></section><div class="grid"><section class="card chat"><header><el-icon><ChatDotRound /></el-icon><div><b>客服试聊</b><small>仅基于知识库回答</small></div></header><div class="answer">{{ answer || '输入一个问题，验证知识库检索与回答效果。' }}</div><el-input v-model="question" type="textarea" :rows="4" placeholder="例如：订单如何发货？"/><el-button type="primary" :loading="asking" @click="ask">开始试聊</el-button></section><section class="card knowledge"><header><el-icon><Document /></el-icon><div><b>知识库管理</b><small>仅管理员可上传与重建</small></div></header><el-upload drag :auto-upload="false" accept=".txt,.md,.pdf" :before-upload="beforeUpload"><el-icon><UploadFilled /></el-icon><div>拖入文件，或 <em>点击选择</em></div><small>支持 TXT / MD / PDF，上传后由服务端切分与向量化</small></el-upload><div v-for="file in files" :key="file.name" class="file"><div><b>{{ file.name }}</b><small>{{ file.size }} · {{ file.chunks }} 个分段</small></div><el-tag :type="file.status === '已向量化' ? 'success' : 'warning'">{{ file.status }}</el-tag></div></section></div><section class="card process"><b>RAG 处理流程</b><div><span>1. 文件解析</span><i>→</i><span>2. 文档切分</span><i>→</i><span>3. Embedding 向量化</span><i>→</i><span>4. 相似度检索</span><i>→</i><span>5. 受控回答</span></div></section></div></template>
<style scoped>.ai-page{max-width:1200px;margin:auto}.hero{display:flex;justify-content:space-between;align-items:start;padding:30px 34px;border-radius:17px;color:#fff;background:linear-gradient(115deg,#202b48,#425f96)}.hero span{color:#ffb38d;font-size:12px;font-weight:700;letter-spacing:1px}.hero h1{margin:9px 0;font-size:28px}.hero p{margin:0;color:#c8d3e9}.grid{display:grid;grid-template-columns:1fr 1.2fr;gap:20px;margin-top:20px}.card{padding:22px;border-radius:14px;background:#fff;border:1px solid #edf0f5}.card header{display:flex;gap:10px;align-items:center;margin-bottom:18px}.card header .el-icon{padding:9px;border-radius:10px;color:#ff6438;background:#fff0e9;font-size:20px}.card b,.card small{display:block}.card small{margin-top:3px;color:#8c97aa;font-size:12px}.answer{min-height:140px;margin-bottom:14px;padding:14px;border-radius:10px;color:#536078;background:#f6f8fc;line-height:1.7}.chat :deep(.el-button){margin-top:12px;width:100%}.knowledge :deep(.el-upload-dragger){padding:23px}.file{display:flex;justify-content:space-between;align-items:center;padding:13px 0;border-bottom:1px solid #eff1f5}.process{margin-top:20px}.process>div{display:flex;align-items:center;gap:14px;margin-top:18px;color:#61708a}.process span{padding:9px 12px;border-radius:9px;background:#f4f6fa;font-size:13px}.process i{color:#ff6338;font-style:normal}@media(max-width:800px){.grid{grid-template-columns:1fr}.process>div{flex-wrap:wrap}}</style>
