server:
  port: ${EASYGOING_PORTAL_PORT:8085}

spring:
  datasource:
    url: ${EASYGOING_PORTAL_DB_URL}
    username: ${EASYGOING_PORTAL_DB_USERNAME}
    password: ${EASYGOING_PORTAL_DB_PASSWORD}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  data:
    mongodb:
      uri: ${EASYGOING_MONGODB_URI}
  redis:
    host: ${EASYGOING_PORTAL_REDIS_HOST}
    database: 0
    port: ${EASYGOING_PORTAL_REDIS_PORT:6379}
    password: ${EASYGOING_PORTAL_REDIS_PASSWORD}
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  rabbitmq:
    host: ${EASYGOING_RABBITMQ_HOST}
    port: ${EASYGOING_RABBITMQ_PORT:5672}
    virtual-host: ${EASYGOING_RABBITMQ_VHOST:/mall}
    username: ${EASYGOING_RABBITMQ_USERNAME}
    password: ${EASYGOING_RABBITMQ_PASSWORD}
    publisher-confirms: true

logging:
  path: ${EASYGOING_LOG_PATH:/var/logs}
